version: "3.9"

services:
  db:
    container_name: mondi_postgres
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER:${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD:${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  api:
    image: ${DOCKERHUB_USERNAME}/mondi-machine:latest
    pull_policy: always
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/machine
      SPRING_DATASOURCE_USERNAME: ${DEV_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
volumes:
  pgdata:
