version: "3.9"

services:
  db:
    container_name: mondi_postgres
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: ${DOCKERHUB_USERNAME}/mondi-machine:latest
    pull_policy: always
    restart: always
    ports:
      - "80:9000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/machine
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
volumes:
  pgdata:
